# Author: Habib Sabiu
# Date: March 31, 2017
# Purpose: Script to plot load average logs generated by Ganglia
# Copyright: Any person can adopt this script to their specific need


from matplotlib.font_manager import FontProperties
from datetime import datetime, timedelta

import csv
import matplotlib.pyplot as plt
import matplotlib.dates as mdates

with open('loadFive.csv', 'rb') as f:
    reader = csv.reader(f)
    data_list = list(reader)

time_stamp_list = []
load_list = []

for index, line in enumerate(data_list):
    if index > 0:
        time_stamp = line[0]
        total_load = (float(line[1]) + float(line[2]) + float(line[3]) + float(line[4]) + float(line[5]) + float(line[6]) + float(line[7]) + float(line[8]) + float(line[9]) + float(line[10]) + float(line[11])) / 11.0

        time_stamp_list.append(datetime.strptime(time_stamp[0:19], "%Y-%m-%dT%H:%M:%S"))
        load_list.append(total_load)

fig, ax = plt.subplots()
plt.title("Image format conversion - YARN", fontsize=20)
plt.ylabel("Average cluster load (%)", fontsize=15)
plt.xlabel("Timestamp", fontsize=15)
#plt.xlim([datetime(2017, 02, 01, 14, 22, 00), datetime(2017, 02, 01, 14, 35, 00)])
plt.ylim([0, 5])

#ax.xaxis.set_major_locator(mdates.SecondLocator(interval=60))
ax.xaxis.set_major_formatter(mdates.DateFormatter('%H:%M:S'))

ax.plot_date(time_stamp_list, load_list, fmt="r*-", label="load", )

# font of the legend
fontP = FontProperties()
fontP.set_size('large')

ax.legend(loc='upper right', shadow=False, prop=fontP)
ax.xaxis.set_major_formatter(mdates.DateFormatter('%H:%M:%S'))
ax.grid(True)
fig.autofmt_xdate()
plt.show()
